spring.application.name=booking-reportng-system

spring.datasource.url=jdbc:mysql://localhost:3306/booking_system_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Automation Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Console logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.com.example.booking_reportng_system=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.root=INFO

#mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=c0aad31c70f0ba
spring.mail.password=e3d3384942493f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Set the automated report recipient
app.report.recipient=manager@travelcorp.com, team@travelcorp.com

# Set the cron schedule (This runs at exactly 9:00 PM every day)
app.report.cron=0 0 21 * * ?